// Constants.h
// Created by Martin Dariush Hansen, 2017-03-04

#pragma once

// Engine
const int STEP_DURATION = 1000000000 / 200;
const int FRAME_DURATION = 1000000000 / 60;

// Graphics
const int TARGET_RESOLUTION_X = 1920;
const int TARGET_RESOLUTION_Y = 1080;
const int MIN_RESOLUTION_X = TARGET_RESOLUTION_X / 4;
const int MIN_RESOLUTION_Y = TARGET_RESOLUTION_Y / 4;
const int MAX_RESOLUTION_X = TARGET_RESOLUTION_X * 4;
const int MAX_RESOLUTION_Y = TARGET_RESOLUTION_Y * 4;
const int DEFAULT_RESOLUTION_X = TARGET_RESOLUTION_X / 2;
const int DEFAULT_RESOLUTION_Y = TARGET_RESOLUTION_Y / 2;
